// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(31, 15));

            // Double-Click 'Del' button
            Mouse.DoubleClick(uIDelButton, new Point(31, 15));

            // Double-Click 'Del' button
            Mouse.DoubleClick(uIDelButton, new Point(31, 15));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(31, 15));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(22, 13));

            // Click '*' button
            Mouse.Click(uIItemButton, new Point(23, 19));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(22, 17));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(50, 17));
        }
        
        /// <summary>
        /// RecordedMethod2
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(27, 21));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(33, 11));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(26, 11));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(15, 7));

            // Click '+' button
            Mouse.Click(uIItemButton3, new Point(20, 13));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(27, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(78, 14));
        }
        
        /// <summary>
        /// RecordedMethod3
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(23, 12));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(31, 4));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(27, 13));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(33, 12));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(26, 9));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(40, 13));
        }
        
        /// <summary>
        /// RecordedMethod4
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton5 = this.UIMyCalculatorv1Window.UIItemButton5;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(33, 15));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(23, 17));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(24, 12));

            // Click '-' button
            Mouse.Click(uIItemButton5, new Point(24, 13));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(28, 4));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(25, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(42, 20));
        }
        
        /// <summary>
        /// RecordedMethod5
        /// </summary>
        public void RecordedMethod5()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Move 'MyCalculator v1' title bar
            Mouse.StartDragging(uIMyCalculatorv1TitleBar, new Point(92, 18), MouseButtons.Left, ModifierKeys.None);
            Mouse.StopDragging(uIMyCalculatorv1TitleBar, 0, -12);

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(18, 16));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(35, 13));

            // Click '+' button
            Mouse.Click(uIItemButton2, new Point(25, 13));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(38, 5));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(29, 15));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(72, 17));
        }
        
        #region Properties
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.Name] = "4";
                    this.mUIItem4Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WpfButton.PropertyNames.Name] = "5";
                    this.mUIItem5Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WpfButton.PropertyNames.Name] = "9";
                    this.mUIItem9Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.Name] = "0";
                    this.mUIItem0Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItemButton5
        {
            get
            {
                if ((this.mUIItemButton5 == null))
                {
                    this.mUIItemButton5 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton5.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton5.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton5;
            }
        }
        
        public WpfTitleBar UIMyCalculatorv1TitleBar
        {
            get
            {
                if ((this.mUIMyCalculatorv1TitleBar == null))
                {
                    this.mUIMyCalculatorv1TitleBar = new WpfTitleBar(this);
                    #region Search Criteria
                    this.mUIMyCalculatorv1TitleBar.SearchProperties[WpfTitleBar.PropertyNames.AutomationId] = "TitleBar";
                    this.mUIMyCalculatorv1TitleBar.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIMyCalculatorv1TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIDelButton;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem4Button;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItem5Button;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem9Button;
        
        private WpfButton mUIItem0Button;
        
        private WpfButton mUIItemButton4;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItemButton5;
        
        private WpfTitleBar mUIMyCalculatorv1TitleBar;
        #endregion
    }
}
